<template>
  <v-container>
    <v-row align="center"
            justify="center">
      <v-col class="text-center"
              cols="12">
        <h1 class="display-1 active-color ma-4">
          Aseguradoras con las que trabajamos
        </h1>
      </v-col>
    </v-row>
    <v-row>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Atlas.png"
                aspect-ratio="1"
        class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/GNP.png"
                aspect-ratio="1"
        class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Afirme.png"
                aspect-ratio="1"
        class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Mapfre.png"
                aspect-ratio="1"
        class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/AXA.png"
                aspect-ratio="1"
        class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Bupa.png"
                aspect-ratio="1"
        class="ma-4"/>
      </v-col>
    </v-row>
    <v-row>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Prudential.png"
                aspect-ratio="1"
                class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Qualitas.png"
                aspect-ratio="1"
                class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Afirme.png"
                aspect-ratio="1"
                class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/BX+.png"
                aspect-ratio="1"
                class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/Metlife.png"
                aspect-ratio="1"
                class="ma-4"/>
      </v-col>
      <v-col
              cols="6"
              lg="2"
              xl="2"
              md="4"
              sm="6">
        <v-img
                src="../assets/companies/CHUBB.png"
                aspect-ratio="1"
                class="ma-4"/>
      </v-col>
    </v-row>
      <v-row
              align="center"
              justify="center">
        <v-col
                cols="6"
                lg="2"
                xl="2"
                md="4"
                sm="6">
          <v-img
                  src="../assets/companies/HDIseguros.png"
                  aspect-ratio="1"
                  class="ma-4"/>
        </v-col>
        <v-col
                cols="6"
                lg="2"
                xl="2"
                md="4"
                sm="6">
          <v-img
                  src="../assets/companies/PrimeroSeguros.png"
                  aspect-ratio="1"
                  class="ma-4"/>
        </v-col>
        <v-col
                cols="6"
                lg="2"
                xl="2"
                md="4"
                sm="6">
          <v-img
                  src="../assets/companies/BanorteSeguros.png"
                  aspect-ratio="1"
                  class="ma-4"/>
        </v-col>

      </v-row>
  </v-container>
</template>

<style lang="scss">
  @import './src/styles/variables.scss';
  .active-color {
    color: #002554 ;
  }

</style>
